### ISSUE TITLE
膜拜大佬

### ISSUE THREAD

**Issue by ShamDay** [ericet/EvmosTestnet#1]
大佬，请问合约json还有https://evmos-evm-rpc.tk/是咋搞的，求指导

**Comment by ericet** [comment]
evmos-evm-rpc.tk 是节点，evmos discord群里找到的
ABI看合约，合约是公开的。或者查看网站源代码也有

**Comment by ShamDay** [comment]
> evmos-evm-rpc.tk 是节点，evmos discord群里找到的 ABI看合约，合约是公开的。或者查看网站源代码也有

谢谢大佬
